### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by yuriescl** [yuriescl/startstop#3]
- [ ] `ttm ls` should order by id by default
- [ ] `NAME` column should display at max 30 chars
- [ ] shorten readme gif duration
- [ ] add memory usage per task
- [ ] create `ttmd`, an optional daemon with features like scheduling and autorestart
- [ ] package software into `.deb`, `.rpm`, etc
- [ ] add `ls-logs` file listing log files instead of contents
- [ ] add support for --param= syntax
- [ ] add timeout to stop()
- [ ] add automated checks/tests via GitHub actions?
- [ ] allow specifying number of lines in 'logs'
- [ ] allow specifying which columns to display in `ls`
- [ ] .ini file - https://docs.python.org/3/library/configparser.html
- [ ] add -q global flag
- [ ] allow start/stop/rm non-parallel
- [ ] test in other Unix-like systems
- [ ] add busy interval parameter used in busy loops
- [ ] add JSON CLI input/output support
- [ ] allow 'ls' sorting
- [ ] add scheduling support?
- [ ] add --shellprog param to specify which shell to use in case of -s
- [ ] add --cwd param
